name: 'Auto Bump'
description: 'A GitHub Action that auto-bumps PRs with changes from their destination branch'
inputs:
  AUTOBUMP_RUN:
    required: true
  AUTOBUMP_USER_NAME:
    required: false
    default: "github-actions"
  AUTOBUMP_USER_EMAIL:
    required: false
    default: "github-actions@github.com"
runs:
  using: "composite"
  steps:
      - name: Setup git
        shell: bash
        run: |
          git config user.name ${{ inputs.AUTOBUMP_USER_NAME }} 
          git config user.email ${{ inputs.AUTOBUMP_USER_EMAIL }}

      - name: Setup npm
        shell: bash
        run: |
          npm config set git-tag-version false

      - name: Run Auto Bump Script
        shell: bash
        run: ${{ github.action_path }}/auto-bump-script.sh
        env:
          AUTOBUMP_RUN: ${{ inputs.AUTOBUMP_RUN }}