name: 'Auto Bump'
description: 'A GitHub Action that auto-bumps PRs with changes from their destination branch'
inputs:
  AUTOBUMP_RUN:
    required: true
runs:
  using: "composite"
  steps:
      - name: Setup git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup npm
        shell: bash
        run: |
          npm config set git-tag-version false

      - name: Run Auto Bump Script
        shell: bash
        run: ${{ github.action_path }}/auto-bump-script.sh
        env:
          AUTOBUMP_RUN: ${{ inputs.AUTOBUMP_RUN }}